# Generated by Django 3.0.3 on 2020-02-21 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('test1', '0002_auto_20200221_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoremodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userss', to=settings.AUTH_USER_MODEL),
        ),
    ]
